# Generated by Django 3.1.8 on 2021-06-01 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('leave_type', models.CharField(max_length=255)),
                ('leave_reason', models.CharField(max_length=255)),
                ('date_filed', models.DateField(max_length=255)),
                ('leave_status', models.CharField(default='Pending', max_length=255)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
