# Generated by Django 3.1.8 on 2021-06-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='date_filed',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved_supervisor', 'Approved by Supervisor'), ('approved_hr', 'Approved by HR')], default='pending', max_length=255),
        ),
    ]
