# Generated by Django 3.1.8 on 2021-06-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_auto_20210623_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='date_filed',
            field=models.DateField(max_length=255),
        ),
    ]
