# Generated by Django 3.1.8 on 2021-06-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_auto_20210624_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved by Supervisor', 'Approved by Supervisor'), ('Approved by HR', 'Approved by HR')], default='Pending', max_length=255),
        ),
    ]
