# Generated by Django 3.1.8 on 2021-06-22 05:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('company_description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('company_address', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
    ]
