# Generated by Django 3.1.8 on 2021-06-01 10:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('datetime_in', models.DateTimeField(auto_now_add=True)),
                ('datetime_out', models.DateTimeField(auto_now=True)),
                ('absent', models.BooleanField(default=False)),
            ],
        ),
    ]
