# Generated by Django 3.1.8 on 2021-06-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='datetime_in',
        ),
        migrations.AddField(
            model_name='attendance',
            name='hours_logged',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='datetime_out',
            field=models.DateTimeField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
