# Generated by Django 3.1.8 on 2021-06-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20210604_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='datetime_in',
            field=models.DateTimeField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
