# Generated by Django 3.1.8 on 2021-06-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='sick_leave_count',
            new_name='leave_count',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='vac_leave_count',
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
