# Generated by Django 3.1.8 on 2021-06-22 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('employees', '0002_auto_20210618_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
    ]
