# Generated by Django 3.1.8 on 2021-06-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_status',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
