# Generated by Django 3.1.8 on 2021-06-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20210623_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department_role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Normal', 'Normal')], default='Normal', max_length=255),
        ),
    ]
