# Generated by Django 3.1.8 on 2021-06-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_department_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_status',
            field=models.CharField(choices=[('Contractual', 'Contractual'), ('Probationary', 'Probationary'), ('Regular', 'Regular')], default=None, max_length=255, null=True),
        ),
    ]
