# Generated by Django 3.1.8 on 2021-06-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_auto_20210623_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_status',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Regular', 'Regular'), ('Contractual', 'Contractual'), ('Probationary', 'Probationary')], default='Unknown', max_length=255),
        ),
    ]
