# Generated by Django 2.2.16 on 2021-06-14 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_auto_20210520_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ('domain',), 'verbose_name': 'site', 'verbose_name_plural': 'sites'},
        ),
    ]
